= CSCI C490 Design Document Requirements

You will create a document to describe the particular Android project you wish to complete for this course.

. Create a new Markdown or Asciidoctor document to replace this readme document.
. Format your document with proper headings, sections, paragraphs, etc.
. Your document should include descriptions of the rest of this document in copmelete and professional prose.

== Section 1 – Motivation for Your App

The app is going to be a minigame app. The idea for the app came from the idea of a carnival that has a bunch of random games you can choose between. All of the games should be relatively short so that the user shouldn't spend more than a minute on each game. The reasoning behind creating short games is so that people can play them when they don't have a long amount of time to commit to playing a full game. Anyone would be able to play the app, but most of its users would come from people ages 10-30.

== Section 2 - Meeting Minimum Requirements

The app will start with a main menu screen. On this screen, there will be buttons to go to each individual game along with a scores menu that will hold the highest scores from all the games. Each game and the high scores will open is new activities in the app. In each activity there will be an option to quit the game and return to the home screen. At the end of each game, the app will save their score and then take them to the high scores page for that particular game. The app will use an MVC to save the user state when switching between configurations.

All the data that comes from the scores will be stored in a database on the app. The app will only need to access the database on the score screens, which can be accessed from the main menu and at the end every game.

=== 2.1 User Interface

1. Must work in both landscape and portrait configuration and not lose any of the user's input when switching between configurations, and/or screens
2. There can be an exception to #1, but in your initial design document, you must make a compelling argument for it to work in only one configuration
3. Must work on both the Samsung Tab A 10.1"
4. There can be an exception to #3, but in your initial design document, you must make a compelling argument for it
to work on only one of these devices
5. You must submit diagrams for all the different screens in your app (both portrait and landscape configurations),
one diagram per screen. These diagrams must clearly show the layout of your app's screens, i.e., where images, menus, widgets, views, etc., appear. These can be hand drawn with a .png submitted of the drawing.

=== 2.2 Data Persistence

1. Your app must demonstrate that it saves data from one use to another
2. To test this, your app will be shut down by an onDestroy() event, and then restarted
3. Data entered in by the user during one use must be present when the app is restarted for another use

=== 2.3 Communication

* Your app must demonstrate that it communicates with the outside world, with either another device or an external resource

== Section 3 – MVC Breakdown of Your App

In this section, you must utilize the MVC Design Pattern to describe each of the screens supported by your app.
There are a couple of ways you might go about organizing this section of your document:

1. This approach uses one design document section per screen – i.e., provide View, Model, and Controller descriptions about each screen, one screen’s MVC set of descriptions after another
2. This approach has three sections, a View section, a Model section, and a Controller section. In the View section provide a description of each screen appearing in your app, in the Model section provide a description of all Java classes used in the model, in the Controller section provide a description of all controllers required by your app

=== 3.1 View Descriptions

Currently, each game isn't completely thought out so the views for each of them will change over time. At the moment, each screen will have at least one button, in order for the user to be able to move around the app. There will be textViews for instructions to play the game and for keeping track of scores.

=== 3.2 Model Descriptions

The scores will need to be stored into the database, possibly combined with names for who achieved the score, so there will need to be methods in the client classes that can access the database. The database will have a table for each game in the app. Each table will consists of an int scores won by the players and a string player name. 

=== 3.3 Controller Descriptions

The controller will override the onCreate method to display the UI elements and to have them wired up with listeners. The data will be saved directly to the viewModel so that they will be preserved across different app states. 